definitions:
  steps:
    - step: &ESLint
        name: eslint
        script:
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use && nvm install 16.15.0
          - npm install
          - npm run lint
    - step: &Prettier
        name: prettier
        script:
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use && nvm install 16.15.0
          - npm install
          - npm run lint
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    master:
      - step: *ESLint
      - step: *ESLint
  tags:
    stage-*:
      - step: *ESLint
