definitions:
  steps:
    - step: &ESLint
        name: eslint
        image: node:16.15.0-alpine
        script:
          - npm install
          - npm run lint
    - step: &Prettier
        image: node:16.15.0-alpine
        name: prettier
        script:
          - npm install
          - npm run lint
pipelines:
  branches:
    master:
      - step: *ESLint
      - step: *Prettier
  tags:
    stage-*:
      - step: *ESLint
