definitions:
  steps:
    - step: &ESLint
        name: eslint
        image: node:16.15.0-alpine
        caches:
          - node
        script:
          - npm install
          - npm run lint
    - step: &Prettier
        image: node:16.15.0-alpine
        name: prettier
        caches:
          - node
        script:
          - npm install
          - npm run lint
    - step: &Rsync
        image: atlassian/default-image:4
        name: rsync
        script:
          - apt-get update && apt-get install -y rsync
          - mkdir -p ~/.ssh
          - echo -n "$SSH_PRIVATE_KEY" | base64 --d > ~/.ssh/id_rsa
          - chmod 700 ~/.ssh
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          - rsync -a -r --progress --human-readable --delete
              --exclude-from '.gitignore'
              --exclude .gitignore
              --exclude .git
              . $SSH_USER@$SSH_HOST:~/bitb_new_folder/
       
pipelines:
  branches:
    master:
      - step: *Rsync
      # - step: *ESLint
      # - step: *Prettier
  tags:
    stage-*:
      - step: *ESLint
