name: Deploy EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SSH key
        run: |
          # створюємо директорию для ключа
          mkdir -p ~/.ssh
          # виводимо содержимое нашей переменной окружения в файл
          echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
          # ставим нужные безопасные права
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: |
          # Добавляем отпечаток сервера
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Copy files to the server
        run: rsync -a -r --progress --human-readable --delete
              --exclude-from '.gitignore'
              --exclude .gitignore
              --exclude .git
              --exclude public
              . $SSH_USER@$SSH_HOST:~/realworld/
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Restart the application
        run: |
          ssh $SSH_USER@$SSH_HOST "pushd ~/realworld && npm install && popd && pm2 restart ecosystem.config.js"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
