name: Deploy EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SSH key
        run: |
          # создаем директорию для ключа
          mkdir -p ~/.ssh
          # выводим содержимое нашей переменной окружения в файл
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/free-aws-sshkey.pem
          # ставим нужные безопасные права
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/free-aws-sshkey.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
          
        run: |
          # Добавляем отпечаток сервера
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Copy files to the server
        run: ls -a ~/.ssh && 
              rsync -avz "ssh -i ~/.ssh/free-aws-sshkey.pem" --progress --human-readable --delete
              --exclude-from '.gitignore'
              --exclude .gitignore
              --exclude .git
              . $SSH_USER@$SSH_HOST:~/app/app_test_folder/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
