name: eslint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:16.15.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint source code with eslint
        run: npm run lint
  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:16.15.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Prettify our source code with Prettier
        run: npm run check:format
